// @generated by scripts/generate-sidebar.mjs — do not edit
import type { DefaultTheme } from 'vitepress'

const sidebar: DefaultTheme.Sidebar = {
  "/notes/": [
    {
      "text": "RISC-V",
      "link": "/notes/riscv/"
    },
    {
      "text": "RTOS",
      "link": "/notes/rtos/"
    },
    {
      "text": "Display",
      "link": "/notes/display/"
    }
  ],
  "/analysis/": [
    {
      "text": "Linux 内核",
      "items": [
        {
          "text": "概览",
          "link": "/analysis/kernel/"
        },
        {
          "text": "USB 子系统",
          "link": "/analysis/kernel/usb/"
        },
        {
          "text": "Pinctrl / GPIO 子系统",
          "link": "/analysis/kernel/pinctrl/"
        },
        {
          "text": "SPI 子系统",
          "link": "/analysis/kernel/spi/"
        },
        {
          "text": "Media / V4L2",
          "link": "/analysis/kernel/media/"
        },
        {
          "text": "Sound / ALSA",
          "link": "/analysis/kernel/sound/"
        },
        {
          "text": "BPF / kprobe",
          "link": "/analysis/kernel/bpf/"
        },
        {
          "text": "调试与实践",
          "items": [
            {
              "text": "概览",
              "link": "/analysis/kernel/debug/"
            },
            {
              "text": "USB",
              "link": "/analysis/kernel/debug/usb/"
            },
            {
              "text": "Pinctrl / GPIO",
              "link": "/analysis/kernel/debug/gpio/"
            },
            {
              "text": "Sound",
              "link": "/analysis/kernel/debug/sound/"
            },
            {
              "text": "写作模板",
              "link": "/analysis/kernel/debug/template"
            }
          ]
        }
      ]
    }
  ]
}

export default sidebar
