#!/usr/bin/env node
/**
 * 从 docs/.vitepress/sidebar.meta.json + 各 md frontmatter 生成侧边栏。
 * frontmatter：sidebarOrder（排序）、sidebarTitle（标题）、sidebarHidden（true 则跳过）
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const DOCS = join(ROOT, 'docs')
const META_PATH = join(DOCS, '.vitepress', 'sidebar.meta.json')
const OUT_PATH = join(DOCS, '.vitepress', 'sidebar.generated.ts')

function parseFrontmatter(content) {
  const fm = {}
  let body = content.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n')
  if (!body.startsWith('---\n')) return { fm, body }
  const end = body.indexOf('\n---\n', 4)
  if (end === -1) return { fm, body }
  const block = body.slice(4, end)
  body = body.slice(end + 5)
  for (const line of block.split('\n')) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
    if (!m) continue
    const key = m[1]
    let val = m[2].trim()
    if (val === 'true') val = true
    else if (val === 'false') val = false
    else if (/^\d+$/.test(val)) val = Number(val)
    fm[key] = val
  }
  return { fm, body }
}

function extractTitle(body, fm) {
  if (fm.sidebarTitle) return String(fm.sidebarTitle)
  if (fm.homeTitle) return String(fm.homeTitle)
  const m = body.match(/^#\s+(.+)$/m)
  if (!m) return '未命名'
  return m[1].replace(/`/g, '').trim()
}

function toLink(relFromDocs) {
  const norm = relFromDocs.replace(/\\/g, '/').replace(/\.md$/, '')
  if (norm.endsWith('/index')) {
    return `/${norm.slice(0, -6)}/`
  }
  return `/${norm}`
}

function readPage(relPath) {
  const abs = join(DOCS, relPath)
  const raw = readFileSync(abs, 'utf8')
  const { fm, body } = parseFrontmatter(raw)
  return { fm, body, relPath: relPath.replace(/\\/g, '/') }
}

function linkToRelPath(link) {
  let rel = link.replace(/^\//, '')
  if (rel.endsWith('/')) rel += 'index.md'
  else rel += '.md'
  return rel
}

function listDirMarkdown(dirRel, { skipIndex = false } = {}) {
  const absDir = join(DOCS, dirRel)
  let entries = []
  try {
    entries = readdirSync(absDir)
  } catch {
    return []
  }
  const pages = []
  for (const name of entries) {
    const rel = join(dirRel, name).replace(/\\/g, '/')
    const abs = join(DOCS, rel)
    if (statSync(abs).isDirectory()) continue
    if (!name.endsWith('.md')) continue
    if (skipIndex && name === 'index.md') continue
    const page = readPage(rel)
    if (page.fm.sidebarHidden === true) continue
    pages.push(page)
  }
  pages.sort((a, b) => {
    const oa = Number(a.fm.sidebarOrder ?? 9999)
    const ob = Number(b.fm.sidebarOrder ?? 9999)
    if (oa !== ob) return oa - ob
    return a.relPath.localeCompare(b.relPath, 'zh-CN')
  })
  return pages.map((p) => ({
    text: extractTitle(p.body, p.fm),
    link: toLink(p.relPath),
    _order: Number(p.fm.sidebarOrder ?? 9999),
  }))
}

function stripOrder(items) {
  return items.map(({ text, link }) => ({ text, link }))
}

function resolveNode(node) {
  if (node.index) {
    return { text: node.text, link: toLink(`${node.index}/index.md`) }
  }
  if (node.file) {
    return { text: node.text, link: toLink(node.file) }
  }
  if (node.dir) {
    const items = stripOrder(listDirMarkdown(node.dir, { skipIndex: node.skipIndex === true }))
    if (!node.text) return items
    return { text: node.text, items }
  }
  if (node.dirs) {
    const merged = node.dirs.flatMap((d) => listDirMarkdown(d))
    merged.sort((a, b) => {
      if (a._order !== b._order) return a._order - b._order
      return a.link.localeCompare(b.link, 'zh-CN')
    })
    return {
      text: node.text,
      items: stripOrder(merged),
    }
  }
  if (node.items) {
    const items = node.items.flatMap((child) => {
      const resolved = resolveNode(child)
      if (!resolved) return []
      return Array.isArray(resolved) ? resolved : [resolved]
    })
    if (node.text) {
      return { text: node.text, items }
    }
    return items
  }
  return null
}

function buildSidebar(meta) {
  const sidebar = {}
  for (const [prefix, nodes] of Object.entries(meta.sections)) {
    sidebar[prefix] = nodes.map(resolveNode).filter(Boolean)
  }
  return sidebar
}

function main() {
  const meta = JSON.parse(readFileSync(META_PATH, 'utf8'))
  const sidebar = buildSidebar(meta)
  const out = `// @generated by scripts/generate-sidebar.mjs — do not edit
import type { DefaultTheme } from 'vitepress'

const sidebar: DefaultTheme.Sidebar = ${JSON.stringify(sidebar, null, 2)}

export default sidebar
`
  writeFileSync(OUT_PATH, out, 'utf8')
  console.log(`>>> sidebar 已生成：${relative(ROOT, OUT_PATH)}`)
}

main()
